#!/bin/bash

jupyter contrib nbextension install
jupyter nbextension enable --py widgetsnbextension
jupyter nbextension install --py jupytext
jupyter nbextension enable --py jupytext
jupyter labextension install jupyterlab-jupytext@0.19
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter lab build
