#!/bin/bash

jupyter lab clean
jupyter serverextension enable --py nbgitpuller --sys-prefix
jupyter labextension install jupyterlab-jupytext@0.19 --no-build
jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.38 --no-build
jupyter labextension install bqplot --no-build
jupyter lab build
jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
jupyter nbextension install --user --py jupytext
jupyter nbextension enable --py jupytext
