#!/bin/bash

jupyter lab clean
jupyter serverextension enable --py nbgitpuller --sys-prefix
jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
jupyter nbextension install --user --py jupytext
jupyter nbextension enable --py jupytext
jupyter labextension install jupyterlab-jupytext@0.19
jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.38
jupyter lab build
